spring:
  application:
    name: item-service
  rabbitmq:
    host: 192.168.200.131
    port: 5672
    username: admin
    password: admin

#server:
#  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
    inetutils:
      ignored-interfaces: # 忽略的网卡
        - VM.*
#       preferred-networks: # 要是用的网卡的网段
#         - 192\.168\.0\..+
---
spring:
  profiles: item1
server:
    port: 8001
---
spring:
  profiles: item2
server:
  port: 8002